name: Selenium - Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0  # Versão do MySQL
        env:
          MYSQL_ROOT_PASSWORD: root  # Senha do usuário root
          MYSQL_DATABASE: users  # Nome do banco de dados
          MYSQL_USER: test_user  # Usuário do banco de dados
          MYSQL_PASSWORD: test_password  # Senha do usuário
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Wait for MySQL to be ready
        run: |
          sleep 20  # Aguarda o MySQL iniciar completamente

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: users
        run: pytest ./tests -v --html=./reports/report.html

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: report
          path: ./reports/report.html
